version: '2'
services:
  todoapi:
    build:
      context: ./
      dockerfile: ./ToDoList.API/Dockerfile
    ports:
      - "8080:80"
      - "443:443"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"